In [124]:
import pandas as pd

In [125]:
books=pd.read_csv('Books.csv')

C:\Users\iaman\AppData\Local\Temp\ipykernel_13848\2241478042.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv('Books.csv')


books mein kitne unique publishers hain? sirf ek line mein nikaal.

In [127]:
books['Publisher'].nunique()

16807

In [128]:
ratings=pd.read_csv('Ratings.csv')
users=pd.read_csv('Users.csv')

users mein Age column mein kitne null values hain? percentage bhi nikaal total ka.

In [130]:
users[users['Age'].isna()]

,User-ID,Location,Age
0,1,"nyc, new york, usa",NaN
2,3,"moscow, yukon territory, russia",NaN
4,5,"farnborough, hants, united kingdom",NaN
6,7,"washington, dc, usa",NaN
7,8,"timmins, ontario, canada",NaN
...,...,...,...
278849,278850,"sergnano, lombardia, italy",NaN
278853,278854,"portland, oregon, usa",NaN
278855,278856,"brampton, ontario, canada",NaN
278856,278857,"knoxville, tennessee, usa",NaN


In [131]:
users[users['Age'].isnull()]

,User-ID,Location,Age
0,1,"nyc, new york, usa",NaN
2,3,"moscow, yukon territory, russia",NaN
4,5,"farnborough, hants, united kingdom",NaN
6,7,"washington, dc, usa",NaN
7,8,"timmins, ontario, canada",NaN
...,...,...,...
278849,278850,"sergnano, lombardia, italy",NaN
278853,278854,"portland, oregon, usa",NaN
278855,278856,"brampton, ontario, canada",NaN
278856,278857,"knoxville, tennessee, usa",NaN


ratings mein Book-Rating ki value counts nikaal — kaunsi rating sabse zyada di gayi hai?

In [133]:
ratings['Book-Rating'].value_counts()

Book-Rating
0     716109
8     103736
10     78610
7      76457
9      67541
5      50974
6      36924
4       8904
3       5996
2       2759
1       1770
Name: count, dtype: int64

books mein Year-Of-Publication column ka dtype kya hai? Agar string hai toh numeric mein convert karo aur invalid values (jo number nahi hain) ko NaN bana do.

In [135]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...


In [136]:
books['Year-Of-Publication'].dtype

dtype('O')

In [137]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...


In [138]:
books['Year-Of-Publication'] = pd.to_numeric(
    books['Year-Of-Publication'],
    errors='coerce'
)
#errors='coerce' -> invalid strings ko forcefully NaN bana deta hai ✅

users ki Location column se sirf country nikaal (last part after last comma) aur ek naya column 'Country' banao.

In [140]:
users

,User-ID,Location,Age
0,1,"nyc, new york, usa",NaN
1,2,"stockton, california, usa",18.0
2,3,"moscow, yukon territory, russia",NaN
3,4,"porto, v.n.gaia, portugal",17.0
4,5,"farnborough, hants, united kingdom",NaN
...,...,...,...
278853,278854,"portland, oregon, usa",NaN
278854,278855,"tacoma, washington, united kingdom",50.0
278855,278856,"brampton, ontario, canada",NaN
278856,278857,"knoxville, tennessee, usa",NaN


In [141]:
users['Location']

0                         nyc, new york, usa
1                  stockton, california, usa
2            moscow, yukon territory, russia
3                  porto, v.n.gaia, portugal
4         farnborough, hants, united kingdom
                         ...                
278853                 portland, oregon, usa
278854    tacoma, washington, united kingdom
278855             brampton, ontario, canada
278856             knoxville, tennessee, usa
278857                  dublin, n/a, ireland
Name: Location, Length: 278858, dtype: object

In [142]:
users['Location'].str.split(',')

0                         [nyc,  new york,  usa]
1                  [stockton,  california,  usa]
2            [moscow,  yukon territory,  russia]
3                  [porto,  v.n.gaia,  portugal]
4         [farnborough,  hants,  united kingdom]
                           ...                  
278853                 [portland,  oregon,  usa]
278854    [tacoma,  washington,  united kingdom]
278855             [brampton,  ontario,  canada]
278856             [knoxville,  tennessee,  usa]
278857                  [dublin,  n/a,  ireland]
Name: Location, Length: 278858, dtype: object

In [143]:
users['Location'].str.split(',').str[-1]

0                     usa
1                     usa
2                  russia
3                portugal
4          united kingdom
               ...       
278853                usa
278854     united kingdom
278855             canada
278856                usa
278857            ireland
Name: Location, Length: 278858, dtype: object

In [144]:
#Extra spaces hatao using str.strip()
users['Location'].str.split(',').str[-1].str.strip()

0                    usa
1                    usa
2                 russia
3               portugal
4         united kingdom
               ...      
278853               usa
278854    united kingdom
278855            canada
278856               usa
278857           ireland
Name: Location, Length: 278858, dtype: object

In [145]:
users['country']=users['Location'].str.split(',').str[-1].str.strip()

In [146]:
users.head(2)

,User-ID,Location,Age,country
0,1,"nyc, new york, usa",NaN,usa
1,2,"stockton, california, usa",18.0,usa


Har author ne kitni books likhi hain? Top 10 authors dikhao jo sabse zyada books likhe hain.

In [148]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988.0,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991.0,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004.0,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996.0,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...


In [149]:
books['Book-Author']

0           Mark P. O. Morford
1         Richard Bruce Wright
2                 Carlo D'Este
3             Gina Bari Kolata
4              E. J. W. Barber
                  ...         
271355          Paula Danziger
271356              Teri Sloat
271357        Christine Wicker
271358                   Plato
271359     Christopher  Biffle
Name: Book-Author, Length: 271360, dtype: object

In [150]:
books.groupby('Book-Author')

In [151]:
books.groupby('Book-Author').size()

Book-Author
 D. Chiel                           1
 J. D. Landis                       1
 Mimma Balia                        1
'N Sync                             1
142 moms from all over the world    1
                                   ..
Â¢ystein LÂ²nn                      1
Ã?dÃ¶n von HorvÃ¡th                 3
Ã?Â?dÃ?Â¶n von Horvath              1
Ã?Â?pictÃ?Â¨te                      1
Ã?Â?ric Holder                      1
Length: 102022, dtype: int64

In [152]:
books.groupby('Book-Author').size().sort_values(ascending=False)

Book-Author
Agatha Christie                632
William Shakespeare            567
Stephen King                   524
Ann M. Martin                  423
Carolyn Keene                  373
                              ... 
margaret Sidney                  1
m Craig Barnes                   1
le Philosophe SÃ?Â©nÃ?Â¨que      1
l. Daniels                       1
ky                               1
Length: 102022, dtype: int64

In [153]:
#Top 10 authors
books.groupby('Book-Author').size().sort_values(ascending=False).head(10)

Book-Author
Agatha Christie        632
William Shakespeare    567
Stephen King           524
Ann M. Martin          423
Carolyn Keene          373
Francine Pascal        372
Isaac Asimov           330
Nora Roberts           315
Barbara Cartland       307
Charles Dickens        302
dtype: int64

In [154]:
users

,User-ID,Location,Age,country
0,1,"nyc, new york, usa",NaN,usa
1,2,"stockton, california, usa",18.0,usa
2,3,"moscow, yukon territory, russia",NaN,russia
3,4,"porto, v.n.gaia, portugal",17.0,portugal
4,5,"farnborough, hants, united kingdom",NaN,united kingdom
...,...,...,...,...
278853,278854,"portland, oregon, usa",NaN,usa
278854,278855,"tacoma, washington, united kingdom",50.0,united kingdom
278855,278856,"brampton, ontario, canada",NaN,canada
278856,278857,"knoxville, tennessee, usa",NaN,usa


In [155]:
ratings

,User-ID,ISBN,Book-Rating
0,276725,034545104X,0
1,276726,0155061224,5
2,276727,0446520802,0
3,276729,052165615X,3
4,276729,0521795028,6
...,...,...,...
1149775,276704,1563526298,9
1149776,276706,0679447156,0
1149777,276709,0515107662,10
1149778,276721,0590442449,10


Har user ne total kitni ratings di hain? Top 5 most active users nikaal.↓
Har user ke ratings count karo

In [157]:
ratings.groupby('User-ID')['Book-Rating'].count()

User-ID
2          1
7          1
8         18
9          3
10         2
          ..
278846     2
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 105283, dtype: int64

In [158]:
ratings.groupby('User-ID')['Book-Rating'].count().sort_values(ascending=False).head(5)

User-ID
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
Name: Book-Rating, dtype: int64

In [159]:
users

,User-ID,Location,Age,country
0,1,"nyc, new york, usa",NaN,usa
1,2,"stockton, california, usa",18.0,usa
2,3,"moscow, yukon territory, russia",NaN,russia
3,4,"porto, v.n.gaia, portugal",17.0,portugal
4,5,"farnborough, hants, united kingdom",NaN,united kingdom
...,...,...,...,...
278853,278854,"portland, oregon, usa",NaN,usa
278854,278855,"tacoma, washington, united kingdom",50.0,united kingdom
278855,278856,"brampton, ontario, canada",NaN,canada
278856,278857,"knoxville, tennessee, usa",NaN,usa


In [160]:
ratings.groupby('User-ID')['Book-Rating'].count()
#har user ne kitni entries (ratings) 

User-ID
2          1
7          1
8         18
9          3
10         2
          ..
278846     2
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 105283, dtype: int64

In [161]:
ratings.groupby('User-ID')['Book-Rating'].count().sort_values(ascending=False).head(5)

User-ID
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
Name: Book-Rating, dtype: int64

Har ISBN ki average rating nikaal — sirf woh ISBNs rakho jinhe minimum 100 ratings mili ho. Result ko avg rating ke basis pe sort karo descending mein.ratings

In [163]:
ratings

,User-ID,ISBN,Book-Rating
0,276725,034545104X,0
1,276726,0155061224,5
2,276727,0446520802,0
3,276729,052165615X,3
4,276729,0521795028,6
...,...,...,...
1149775,276704,1563526298,9
1149776,276706,0679447156,0
1149777,276709,0515107662,10
1149778,276721,0590442449,10


In [164]:
ratings.groupby('ISBN')['Book-Rating'].count()

ISBN
 0330299891    2
 0375404120    2
 0586045007    1
 9022906116    2
 9032803328    1
              ..
cn113107       1
ooo7156103     1
§423350229     1
´3499128624    1
Ô½crosoft      1
Name: Book-Rating, Length: 340556, dtype: int64

In [165]:
#Har ISBN ke ratings count nikalo
isbn_counts = ratings.groupby('ISBN')['Book-Rating'].count()

In [166]:
isbn_counts[isbn_counts>=100]

ISBN
002542730X    171
0060008032    104
0060096195    107
006016848X    147
0060173289    130
             ... 
1573227331    105
1573229326    217
1573229571    106
1592400876    120
1878424319    133
Name: Book-Rating, Length: 731, dtype: int64

In [167]:
isbn_counts[isbn_counts>=100]

ISBN
002542730X    171
0060008032    104
0060096195    107
006016848X    147
0060173289    130
             ... 
1573227331    105
1573229326    217
1573229571    106
1592400876    120
1878424319    133
Name: Book-Rating, Length: 731, dtype: int64

In [168]:
valid_isbns = isbn_counts[isbn_counts >= 100].index

In [169]:
valid_isbns

Index(['002542730X', '0060008032', '0060096195', '006016848X', '0060173289',
       '0060175400', '006019491X', '0060199652', '0060391626', '0060392452',
       ...
       '1558744630', '1558745157', '1559029838', '1573225517', '1573225789',
       '1573227331', '1573229326', '1573229571', '1592400876', '1878424319'],
      dtype='object', name='ISBN', length=731)

In [170]:
filtered_ratings = ratings[ratings['ISBN'].isin(valid_isbns)]

In [171]:
filtered_ratings

,User-ID,ISBN,Book-Rating
2,276727,0446520802,0
8,276744,038550120X,7
10,276746,0425115801,0
11,276746,0449006522,0
12,276746,0553561618,0
...,...,...,...
1149749,276690,0064400557,0
1149761,276704,0345386108,6
1149768,276704,0446605409,0
1149771,276704,0743211383,7


In [172]:
avg_rating = filtered_ratings.groupby('ISBN')['Book-Rating'].mean()

In [173]:
result = avg_rating.sort_values(ascending=False)

In [174]:
result.head()

ISBN
0439064864    6.611765
0439139597    6.541237
0439136350    6.467005
0590353403    6.363095
043935806X    5.571856
Name: Book-Rating, dtype: float64

Har publisher ne kitne books publish kiye — sirf woh publishers rakho jinhone 50 se zyada books publish ki hain. Unhe sort karo descending mein.

In [176]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...


In [177]:
publisher_counts = books.groupby('Publisher')['Book-Title'].count()

In [178]:
publisher_counts[publisher_counts > 50].sort_values(ascending=False)

Publisher
Harlequin                             7535
Silhouette                            4220
Pocket                                3905
Ballantine Books                      3783
Bantam Books                          3646
                                      ... 
Everyman's Library                      51
Cornell University Press                51
Cook Communications Ministries (J)      51
W.W. Norton &amp; Company Ltd           51
Warner Forever                          51
Name: Book-Title, Length: 711, dtype: int64

groupby ke saath .agg() use karo — har ISBN ke liye ek saath count, mean, aur max rating ek hi DataFrame mein nikaal. Columns ka naam rakho: num_ratings, avg_rating, max_rating.

In [180]:
ratings

,User-ID,ISBN,Book-Rating
0,276725,034545104X,0
1,276726,0155061224,5
2,276727,0446520802,0
3,276729,052165615X,3
4,276729,0521795028,6
...,...,...,...
1149775,276704,1563526298,9
1149776,276706,0679447156,0
1149777,276709,0515107662,10
1149778,276721,0590442449,10


In [181]:
ratings.groupby('ISBN')['Book-Rating'].agg(['count', 'mean', 'max'])

,count,mean,max
ISBN,,,
0330299891,2,3.0,6
0375404120,2,1.5,3
0586045007,1,0.0,0
9022906116,2,3.5,7
9032803328,1,0.0,0
...,...,...,...
cn113107,1,0.0,0
ooo7156103,1,7.0,7
§423350229,1,0.0,0


In [182]:
ratings.groupby('ISBN')['Book-Rating'] .agg(num_ratings='count',avg_rating='mean',max_rating='max')

,num_ratings,avg_rating,max_rating
ISBN,,,
0330299891,2,3.0,6
0375404120,2,1.5,3
0586045007,1,0.0,0
9022906116,2,3.5,7
9032803328,1,0.0,0
...,...,...,...
cn113107,1,0.0,0
ooo7156103,1,7.0,7
§423350229,1,0.0,0


2000 ke baad publish hue sabhi books nikaal jo "Stephen King" ne likhi hain.

In [184]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...


In [241]:
df=books[books['Book-Author']=='Stephen King']

In [247]:
df2=df[df['Year-Of-Publication']>=2000]

In [251]:
df2['Book-Title']

126                           The Girl Who Loved Tom Gordon
346                                        Mientras Escribo
502                                             The Shining
881                                            Dreamcatcher
925                                           The Dead Zone
                                ...                        
263349            LA Milla Verde: (El Pasillo De LA Muerte)
263562                   On Writing : A Memoir Of The Craft
266361                                  Los Ojos del Dragon
270899    Secret Windows: Essays and Fiction on the Craf...
271106               El Misterio De Salem's Lot/Salem's Lot
Name: Book-Title, Length: 169, dtype: object

In [253]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...


In [255]:
df=books[books['Year-Of-Publication']>2000]

In [257]:
df2=df[df['Book-Author']=='Stephen King']

In [259]:
df2.loc[1:2]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L


In [261]:
df2[['Book-Title','Book-Author']]

,Book-Title,Book-Author
346,Mientras Escribo,Stephen King
502,The Shining,Stephen King
881,Dreamcatcher,Stephen King
925,The Dead Zone,Stephen King
1651,Pet Sematary,Stephen King
...,...,...
259410,La TempÃ?Âªte du siÃ?Â¨cle,Stephen King
263231,From a Buick 8 : A Novel,Stephen King
263349,LA Milla Verde: (El Pasillo De LA Muerte),Stephen King
266361,Los Ojos del Dragon,Stephen King


Sirf woh ratings rakho jo 0 se zyada hain (explicit ratings). Percentage nikaal total ratings ka kitna % explicit hai.de

In [270]:
total_ratings = len(ratings)
ratings

,User-ID,ISBN,Book-Rating
0,276725,034545104X,0
1,276726,0155061224,5
2,276727,0446520802,0
3,276729,052165615X,3
4,276729,0521795028,6
...,...,...,...
1149775,276704,1563526298,9
1149776,276706,0679447156,0
1149777,276709,0515107662,10
1149778,276721,0590442449,10


In [268]:
total_ratings

1149780

In [272]:
explicit_count=len(ratings[ratings['Book-Rating']>0])

In [276]:
percentage = (explicit_count / total_ratings) * 100

In [278]:
percentage

37.71773730626728

Users jinka age 13 se 17 ke beech hai (inclusive) nikaal — teen readers. Unka count nikaal. Age ke nulls ko pehle drop karo.

In [282]:
users_clean=users.dropna(subset=['Age'])

In [284]:
users_clean[(users_clean['Age']<=17) & (users_clean['Age']>=13)].shape[0]

10844

Books jinka title mein "Harry Potter" word hai unhe nikaal. Book-Author bhi dekho — kitne alag authors listed hain? (hint: same book ke alag ISBNs hote hain)

In [287]:
books[['Book-Title','Book-Author']]

,Book-Title,Book-Author
0,Classical Mythology,Mark P. O. Morford
1,Clara Callan,Richard Bruce Wright
2,Decision in Normandy,Carlo D'Este
3,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata
4,The Mummies of Urumchi,E. J. W. Barber
...,...,...
271355,There's a Bat in Bunk Five,Paula Danziger
271356,From One to One Hundred,Teri Sloat
271357,Lily Dale : The True Story of the Town that Ta...,Christine Wicker
271358,Republic (World's Classics),Plato


.str.contains() → string search
"Harry Potter" → keyword match
na=False → NaN values ko ignore

In [289]:
hp_books=books[books['Book-Title'].str.contains("Harry Potter", na=False)]

In [291]:
hp_books[['Book-Title', 'Book-Author']]

,Book-Title,Book-Author
821,The Sorcerer's Companion: A Guide to the Magic...,ALLAN ZOLA KRONZEK
2143,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling
2809,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling
3459,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling
3839,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling
...,...,...
247872,Harry Potter Fun Book,Warner Bros.
251233,Harry Potter y El Caliz de Fuego,J. K. Rowling
256403,Harry Potter and the Bible: The Menace Behind...,Richard Abanes
257263,Harry Potter and the Goblet of Fire (Harry Pot...,J. K. Rowling


In [293]:
hp_books['Book-Author'].nunique()

27

isin() use karke — woh users nikaal jinki User-ID in hain: [276725, 276726, 276727, 276729]. Unki saari ratings dikhao. Phir ~isin() se yeh users hatao aur remaining count print karo.

In [296]:
selected_users = [276725, 276726, 276727, 276729]

In [298]:
ratings['User-ID']

0          276725
1          276726
2          276727
3          276729
4          276729
            ...  
1149775    276704
1149776    276706
1149777    276709
1149778    276721
1149779    276723
Name: User-ID, Length: 1149780, dtype: int64

In [300]:
ratings[ratings['User-ID'].isin(selected_users)]

,User-ID,ISBN,Book-Rating
0,276725,034545104X,0
1,276726,0155061224,5
2,276727,0446520802,0
3,276729,052165615X,3
4,276729,0521795028,6


In [302]:
#In users ko REMOVE karo
remaining = ratings[~ratings['User-ID'].isin(selected_users)]

In [304]:
remaining

,User-ID,ISBN,Book-Rating
5,276733,2080674722,0
6,276736,3257224281,8
7,276737,0600570967,6
8,276744,038550120X,7
9,276745,342310538,10
...,...,...,...
1149775,276704,1563526298,9
1149776,276706,0679447156,0
1149777,276709,0515107662,10
1149778,276721,0590442449,10


In [306]:
remaining.shape[0]

1149775

ratings aur books ko ISBN column pe merge karo (inner join). Naye DataFrame ka shape print karo aur samjhao kyun rows original ratings se kam hain.')

Inner join logic:
Sirf woh rows aayengi jinka ISBN dono tables me present hai
Agar ISBN match nahi hua → row drop ho jaati hai

In [308]:
merged_df=pd.merge(ratings,books,on='ISBN',how='inner')

In [310]:
merged_df.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002.0,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001.0,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996.0,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999.0,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001.0,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...


You want to build a Collaborative Filtering Based Recommender System, and first step is:
“Find only those users who are active enough (have rated more than 200 books), so that recommendations become reliable.”

In [312]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [314]:
ratings_with_name.groupby('User-ID')

In [316]:
#Count ratings per user
ratings_with_name.groupby('User-ID').count()['Book-Rating']


User-ID
2          1
8         17
9          3
10         1
12         1
          ..
278846     1
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 92106, dtype: int64

In [328]:
#filter
ratings_with_name.groupby('User-ID').count()['Book-Rating']>200


User-ID
2         False
8         False
9         False
10        False
12        False
          ...  
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Rating, Length: 92106, dtype: bool

Keep only True users -> x[x] 👉 only True values remain 🧠 Why >200 threshold?
Get User IDs
.index 👉 final list of “active users”
Because:
low ratings users = noisy data
high ratings users = stable preferences
better similarity calculation

agar koi user sirf 2-3 books rate karta hai, uski preference reliable nahi hogi. Toh sirf woh users lo jinki "reading history" strong hai — 200+ books rate ki ho. x ek True/False Series hai. x[x] sirf True wale rakhta hai. .index se User-IDs milti hain.

| User | Likes                |
| ---- | -------------------- |
| A    | Harry Potter, LOTR   |
| B    | Harry Potter, Hobbit |
| C    | LOTR, Hobbit      

👉 If A and B are similar → recommend B’s books to A   |


In [322]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
active_users = x[x].index

In [324]:
x

User-ID
2         False
8         False
9         False
10        False
12        False
          ...  
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Rating, Length: 92106, dtype: bool

In [330]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(active_users)]

Same logic books ke liye — agar kisi book ko sirf 3 logon ne rate kiya, uska similarity score noise hoga. Minimum 50 ratings wali books lo.

In [332]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994.0,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995.0,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974.0,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982.0,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002.0,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...,...,...
1029357,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002.0,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1029358,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993.0,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...
1029359,275970,3829021860,0,The Penis Book,Joseph Cohen,1999.0,Konemann,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...
1029360,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995.0,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...


In [334]:
filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    False
 Always Have Popsicles                                                                                        False
 Apple Magic (The Collector's series)                                                                         False
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   False
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                False
                                                                                                              ...  
Ã?Â?ber das Fernsehen.                                                                                        False
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           False
Ã?Â?lpiraten.                                                

| Book | Ratings |
| ---- | ------- |
| A    | 2       |
| B    | 10      |
| C    | 500  

“Books jinko enough logon ne rate kiya hai”   |


In [336]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50
famous_books = y[y].index
#Keep only True books y[y] 👉 only popular books remain

# FINAL STEP: Pivot Table (CORE IDEA)

BEFORE:

User1 → BookA → 5
User2 → BookA → 0
User3 → BookA 4 →

AFTER:

            User1  User2  User3
BookA         5      0      4
BookB         0      3     0 4

In [338]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [342]:
pt = final_ratings.pivot_table(
    index='Book-Title',
    columns='User-ID',
    values='Book-Rating'
)

WHY pivot table?

Because collaborative filtering needs:

“Item-user matrix”

So we can compare:

Book vs Book similarity
User pattern similarity

In [344]:
pt.head()

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [351]:
pt.fillna(0, inplace=True)

# working

Users ka kaam tha:
“Books ko compare karne ke liye behavior provide karna”

| Book \ User | U1 | U2 | U3 | U4 |
| ----------- | -- | -- | -- | -- |
| Book A      | 5  | 0  | 3  | 0  |
| Book B      | 0  | 4  | 0  | 2  |
| Book C      | 1  | 1  | 0  | 5  |

cosine_similarity(pt) kya karta hai?
cosine_similarity(pt)

👉 Har row (book) ko ek vector maanta hai

Book A = [5, 0, 3, 0]
Book B = [0, 4, 0, 2]
Book C = [1, 1, 05], 

Step 2: Pairwise comparison

Cosine similarity har pair compare karta hai:

Book A vs Book B
Book A vs Book C
Book B vs Book C

Step 3: Formula behind scenes

cos(θ)=A⋅B/∥A∥∥B∥

If two books:
same users rate same way → similarity HIGH (≈1)
different users → similarity LOW (≈0)
📊 4. Output: similarity_scores
similarity_scores = cosine_similarity(pt)


Why this is used in recommendation system?

When user likes Book A: 👉 system checks:
similarity_scores[A] → top similar books 👉 and recommends them5]

In [355]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores = cosine_similarity(pt)
similarity_scores.shape

(706, 706)

Output: similarity_scores
|   | A   | B   | C   |
| - | --- | --- | --- |
| A | 1.0 | 0.2 | 0.8 |
| B | 0.2 | 1.0 | 0.1 |
| C | 0.8 | 0.1 | 1.0 |


| Book \ User | U1 | U2 | U3 |
| ----------- | -- | -- | -- |
| A           | 5  | 0  | 3  |
| B           | 5  | 0  | 2  |
| C           | 0  | 4  | 0“Kaun si books same users ne same tarah rate ki?”

👉 isse banta hai:

Book A ≈ Book B
Book A ≠ Book C

✅ STEP 1: User ne ek book padhi

Example: 👉 User X liked:
Book A
✅ STEP 2: system check karega similarity
similarity_scores['Book A']

👉 output:

Book B → 0.9
Book C → 0.2
Book D → 0.8

✅ STEP 3: top similar books pick

👉 system selects:

Book B
Book D
🎯 FINAL RESULT: “User X ko Book B aur Book D recommend karo”  |


In [373]:
book_name = "The Shining"

In [375]:
import numpy as np

In [377]:
np.where(pt.index == "A Bend in the Road") #ye tuple hai

(array([4]),)

In [379]:
np.where(pt.index == "A Bend in the Road")[0]

array([4])

In [381]:
np.where(pt.index == "A Bend in the Road")[0][0]

np.int64(4)

In [383]:
x = np.int64(4)
print(x)

4


In [385]:
book_name = "A Bend in the Road"

In [391]:
# kis row pe hai similarity matrix me?
index = np.where(pt.index == book_name)[0][0]

In [393]:
#Us book ki similarity row lo
similarity_scores[index]
#har book se kitni similar hai

array([0.05367224, 0.1095379 , 0.06909024, 0.        , 1.        ,
       0.1013312 , 0.09627016, 0.03993342, 0.07452159, 0.        ,
       0.0530616 , 0.00616629, 0.03418429, 0.04942968, 0.1289979 ,
       0.08192427, 0.19985266, 0.08880666, 0.10177542, 0.13586621,
       0.        , 0.        , 0.03229365, 0.10584252, 0.29562612,
       0.12047151, 0.07456711, 0.10458247, 0.03601541, 0.04888169,
       0.01754798, 0.03365952, 0.05223377, 0.18909339, 0.        ,
       0.16137408, 0.08068053, 0.0416527 , 0.05964277, 0.12075564,
       0.        , 0.10738992, 0.03951803, 0.25099279, 0.03148457,
       0.09572116, 0.        , 0.0908854 , 0.0648952 , 0.06310897,
       0.01245924, 0.        , 0.09978939, 0.        , 0.1620452 ,
       0.04975287, 0.0657618 , 0.20838265, 0.04113637, 0.06087709,
       0.0406275 , 0.10310093, 0.1068425 , 0.1584111 , 0.08301227,
       0.04749344, 0.086492  , 0.        , 0.1660846 , 0.08418528,
       0.        , 0.07096117, 0.        , 0.08642273, 0.10773

In [395]:
# Har similarity ko book index ke saath pair karo
list(enumerate(similarity_scores[index]))

[(0, np.float64(0.053672244225442485)),
 (1, np.float64(0.10953789733294741)),
 (2, np.float64(0.06909024214591328)),
 (3, np.float64(0.0)),
 (4, np.float64(1.0)),
 (5, np.float64(0.10133120190422104)),
 (6, np.float64(0.09627015869844611)),
 (7, np.float64(0.039933422958493336)),
 (8, np.float64(0.07452158863876493)),
 (9, np.float64(0.0)),
 (10, np.float64(0.053061604331357225)),
 (11, np.float64(0.006166291672978489)),
 (12, np.float64(0.034184285395816506)),
 (13, np.float64(0.049429679670861135)),
 (14, np.float64(0.12899789835797454)),
 (15, np.float64(0.08192426594036471)),
 (16, np.float64(0.1998526607378485)),
 (17, np.float64(0.08880666054569399)),
 (18, np.float64(0.10177541679374065)),
 (19, np.float64(0.13586621177840782)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.032293651665519715)),
 (23, np.float64(0.10584251806170297)),
 (24, np.float64(0.2956261183177974)),
 (25, np.float64(0.12047151286571994)),
 (26, np.float64(0.07456711015965088)),
 (27,

In [ ]:
#Sort by similarity (descending)
sorted(list(enumerate(similarity_scores[index])),
       key=lambda x: x[1],
       reverse=True)

In [ ]:
sorted(list(enumerate(similarity_scores[index])),
       key=lambda x: x[1],
       reverse=True)[1:]


Top 3–5 similar books lo
top_books = [(2, 0.85), (4, 0.76), (3, 0.40)]
📌 STEP 8: Ab real book names nikalo
pt.index[2]
pt.index[4]
pt.index[3]

Original dataset se details lo
books[books['Book-Title'] == pt.index[2]]

In [ ]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5] #👉 index + similarity pair
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [ ]:
recommend('1984')

In [ ]:
books.drop_duplicates('Book-Title')

In [ ]:
import pickle

In [ ]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))

In [ ]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

In [ ]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_rating_df

In [ ]:

print(ratings_with_name['Book-Rating'].dtype)
print(ratings_with_name['Book-Rating'].head(10))
#Agar dtype object dikhe ya values mein quotes hoon — yehi problem hai.

In [ ]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

User enters book name
        ↓
FastAPI receives request
        ↓
Recommendation logic runs
        ↓
JSON response returns